### ISSUE TITLE
'surdocs init' fails with no additional information/logs

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#8] opened 2023-07-03 14:44 UTC
Hello, I am evaluating Sureal Docs at the moment, and it appears to be non-functional. I have installed `SurrealDocs-v1.0.5` via the installer, and have confirmed that an installation exists in `C:\Program Files\Medelfor\SurrealDocs\`.

The `surdocs` command apparently wasn't added to PATH and I'm unable to do so manually at this time, so I tried executing from the surdocs.exe file directly. Something along the lines of `'/c/Program Files/Medelfor/SurrealDocs/surdocs.exe' init` (git bash). I also tried triggering the .exe without any arguments, to try and drop into some kind of CLI session. 

I also tried navigating into the installation, and triggering there, just to see what would happen: `.\surdocs.exe init`. 

In all cases, the command executes with no feedback or logs of any kind. Logs are not available at `%appdata%/Medelfor/SurrealDocs/logs/` either.

**Comment by alicewlx** [comment] 2023-07-03 15:18
Hi @SirLich, sorry for the inconvenience!

Can you confirm, that during installation there was a screen with the message about installation being successfully finished? Were there any problems during installation? Could you please provide a list of files/folders inside `C:\Program Files\Medelfor\SurrealDocs\`?

Also we do not recommend using git bash, PowerShell or Cmd would be more appropriate.

**Comment by alicewlx** [comment] 2023-07-03 15:27
You can also run the installer again to see whether that fixes the issue

**Comment by SirLich** [comment] 2023-07-03 16:26
I hope a screenshot suffices: 
![image](https://github.com/medelfor/surreal-docs/assets/18729296/664bece5-bc11-41bd-ae2b-f0ec95f9789c)

I tried with command/powershell/bash, and all of them had the same behavior. 

I did try reinstalling, and on the second installation I deselected Node, and only installed the 'Core' and 'CLI' components. 

I didn't notice anything particularly weird about the installation, other than it seemed to install a lot of random stuff (Chocolaty, Python, etc). I think this was due to the node install though.

**Comment by alicewlx** [comment] 2023-07-03 16:35
Thanks for additional info!

After you reinstalled the tool, did you try to start it? Can you also check whether the `surdocs.exe` indeed is in `%PATH%`?

**Comment by SirLich** [comment] 2023-07-03 16:41
Yes, I tried starting/reinstalling a number of times. `surdocs` was never properly added to the PATH, which is why I was trying to execute it from the .exe directly.

I guess something just went wrong with the installation. I will try again tomorrow, paying closer attention to the logging, and confirming the 'Successfully Installed' screen shows.

The only guess I can make is that some components may have been installed into the Admin account which I used to run the installer, rather than the User account that I am planning on running Surdocs under. I don't know if this flow is supported. 

Anyhow, I will need to try tomorrow. Thanks for the support!

**Comment by alicewlx** [comment] 2023-07-03 16:51
> The only guess I can make is that some components may have been installed into the Admin account which I used to run the installer, rather than the User account that I am planning on running Surdocs under. I don't know if this flow is supported.

We'll try to repeat these steps. If we're able to reproduce and fix the issue, it'll be included into `1.1.0` version we're releasing in a few days

**Comment by alicewlx** [comment] 2023-07-03 17:16
I've confirmed that Surreal Docs should be installed and run under the same user, since it appends `PATH` for that user only, who performs the installation. Besides `PATH`, the installer adds entries to the registry under `HKCU` and writes vital files to `%appdata%` of that user only. All that makes the flow you've described unsupported.

We're sorry that wasn't in the documentation. We'll add this information to the docs of `1.1.0`.

In case you try to run the tool with the same user it was installed under, please let me know the results.

**Comment by SirLich** [comment] 2023-07-04 12:13
Thanks for the continued support. I've continued my evaluation using the admin account directly. Please feel free to close this one.

**Comment by alicewlx** [comment] 2023-07-04 13:01
@SirLich  good to hear!

We've added experimental multi-user installation to `1.1.0` installer and will release it very soon.
Closing the issue as requested.

**Closed by alicewlx** 2023-07-04 13:01 UTC
Labels: documentation
